/home1/zhejianz/.conda/envs/hgf/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home1/zhejianz/.conda/envs/hgf did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
Random seed: 1
11/21/2023 16:27:28 - INFO - root - Initializing Tag System
11/21/2023 16:27:28 - INFO - root - Preparing Data
Some weights of the model checkpoint at xlnet-large-cased were not used when initializing XLNetModel: ['lm_loss.weight', 'lm_loss.bias']
- This IS expected if you are initializing XLNetModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing XLNetModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "/home1/zhejianz/parsing-as-tagging/run.py", line 627, in <module>
    main()
  File "/home1/zhejianz/parsing-as-tagging/run.py", line 621, in main
    predict_command(args)
  File "/home1/zhejianz/parsing-as-tagging/run.py", line 604, in predict_command
    json.dump(pred_output, fout)
  File "/home1/zhejianz/.conda/envs/hgf/lib/python3.10/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home1/zhejianz/.conda/envs/hgf/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home1/zhejianz/.conda/envs/hgf/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home1/zhejianz/.conda/envs/hgf/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home1/zhejianz/.conda/envs/hgf/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/home1/zhejianz/.conda/envs/hgf/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/home1/zhejianz/.conda/envs/hgf/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
